#!/bin/sh

if [ "$#" -ne 1 ] ; then
    echo "Usage: build-sgt-debpkg library (opencv, flycap or spinnaker)" 1>&2
    exit 0
fi

cd SimpleGazeTracker
./gen_docfiles
mv debian_$1 debian
dpkg-buildpackage
make distclean
mv debian debian_$1
cd ..

