.TH GAZEPARSER_VIEWER 1 "April  4, 2013"
.SH NAME
gazeparser_viewer \- GazeParser Data Viewer
.SH SYNOPSIS
.B gazeparser_viewer
.SH DESCRIPTION
Start GazeParser Data Viewer.
Configuration file is created at $HOME/.GazeParser/app
.SH OPTIONS
This program has no commandline options.
.SH AUTHOR
gazeparser_viewer was written by Hiroyuki Sogo <hsogo@ehime-u.ac.jp>.
.PP
This manual page was written by Hiroyuki Sogo <hsogo@ehime-u.ac.jp>,
for the Debian project (and may be used by others).
.SH SEE ALSO
.PP
http://gazeparser.sourceforget.net/

