.TH SGTSRV 1 "April  4, 2013"
.SH NAME
sgtsrv \- SimpleGazeTracker server (OpenCV edition)
.SH SYNOPSIS
.B sgtsrv
.SH DESCRIPTION
Starts SimpleGazeTracker server.
Configuration file is created at $HOME/.SimpleGazeTracker.
Log and data files are created at $HOME/SimpleGazeTracker.
.SH OPTIONS
This program has no commandline options.
.SH AUTHOR
sgtsrv was written by Hiroyuki Sogo <hsogo@ehime-u.ac.jp>.
.PP
This manual page was written by Hiroyuki Sogo <hsogo@ehime-u.ac.jp>,
for the Debian project (and may be used by others).
.SH SEE ALSO
.PP
http://gazeparser.sourceforget.net/

